services:
  # Postgres Database
  database:
    container_name: witsDB
    restart: unless-stopped
    build:
      context: database
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - wits:/var/lib/postgresql/data
      - ./database/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./database/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wits
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # PGAdmin
  pgadmin:
    depends_on:
      - database
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - wits

  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
      - rabbit_data:/var/lib/rabbitmq
      - rabbit_log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_LOAD_DEFINITIONS=/etc/rabbitmq/definitions.json
    networks:
      - wits

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - wits


  # ingest/nwws
  nwws:
    depends_on:
      - rabbit
    image: ghcr.io/therangicrew/wits/ingest/nwws:main
    container_name: nwwsoi
    restart: unless-stopped
    ports:
      - 5222:5222
    environment:
      - RABBIT=${RABBIT}
      - NWWSOI_SERVER=${NWWSOI_SERVER}
      - NWWSOI_ROOM=${NWWSOI_ROOM}
      - NWWSOI_USER=${NWWSOI_USER}
      - NWWSOI_PASS=${NWWSOI_PASS}
      - NWWSOI_RESOURCE=${NWWSOI_RESOURCE}
    networks:
      - wits

  # parsing/awips
  awips:
    depends_on:
      database:
        condition: service_healthy
      rabbit:
    image: ghcr.io/therangicrew/wits/parsing/awips:main
    container_name: awips
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBIT=${RABBIT}
    networks:
      - wits

# Volumes
volumes:
  wits:
    name: wits
  pgadmin:
    name: pgadmin
  rabbit_data:
  rabbit_log:

    # Networks
networks:
  wits:
    name: wits
